spring.application.name=api-gateway

jwt.secret=${JWT_SECRET:defaultSuperSecretKeyForJwtTokenThatIsLongEnough12345}

services.auth.url=${AUTH_SERVICE_URL:http://localhost:8081}
services.user.url=${USER_SERVICE_URL:http://localhost:8080}