apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway

          image: api-gateway-api-gateway:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: JWT_SECRET
              value: superSecretKeyThatIsLongEnoughForJwt123456789

            - name: AUTH_SERVICE_URL
              value: http://auth-service:8080

            - name: USER_SERVICE_URL
              value: http://user-service:8080

            - name: ORDER_SERVICE_URL
              value: http://order-service:8080

            - name: PAYMENT_SERVICE_URL
              value: http://payment-service:8080

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5